"""Unofficial SDK for owner-controlled Matic robots."""

from __future__ import annotations

from matic_sdk.client import MaticClient
from matic_sdk.commands import CommandExecutor, JsonlAuditLog
from matic_sdk.config import MaticConfig, SecurityMode, TlsConfig
from matic_sdk.coverage import (
    CoverageDecodeError,
    ReprioritizationSnapshot,
)
from matic_sdk.credentials import BotToken, CredentialStore
from matic_sdk.models.control import (
    AddZones,
    CleaningFloor,
    ControlCommand,
    CoverageAction,
    CoverageBehavior,
    CoverageCleaningMode,
    CoverageCommand,
    CoverageGoalCleaningMode,
    CoverageGoals,
    CoverageGoalSetting,
    CoverageGoalSpec,
    CoveragePlanGoal,
    CoverageSetting,
    CustomScheduleTarget,
    DrawnCircle,
    JoystickCommand,
    MapEnvironmentAction,
    MapEnvironmentCommand,
    MapPoint,
    MergeRooms,
    MissionPosture,
    NavigationCommand,
    NavigationMode,
    RawMotorCommand,
    RemoveZones,
    RenameRoom,
    ReprioritizeAction,
    ReprioritizeCoverageCommand,
    RoomLabel,
    ScheduleAction,
    ScheduleCommand,
    ScheduleCoverageSetting,
    ScheduleDuration,
    ScheduleEnabledState,
    ScheduleEvent,
    ScheduleEventKey,
    ScheduleTime,
    SemanticsOverride,
    SemanticsOverrideKind,
    SinkSummonLocation,
    SinkSummonScheduleEvent,
    SplitRoom,
    StainMode,
    StandardScheduleTarget,
    UserAction,
    UserCommand,
    Weekday,
)
from matic_sdk.protocol.collections import KNOWN_TARGETS, RawCollectionEvent
from matic_sdk.protocol.commands import COMMAND_REGISTRY, COMMAND_SPECS

__version__ = "0.1.0a1"

__all__ = [
    "COMMAND_REGISTRY",
    "COMMAND_SPECS",
    "KNOWN_TARGETS",
    "AddZones",
    "BotToken",
    "CleaningFloor",
    "CommandExecutor",
    "ControlCommand",
    "CoverageAction",
    "CoverageBehavior",
    "CoverageCleaningMode",
    "CoverageCommand",
    "CoverageDecodeError",
    "CoverageGoalCleaningMode",
    "CoverageGoalSetting",
    "CoverageGoalSpec",
    "CoverageGoals",
    "CoveragePlanGoal",
    "CoverageSetting",
    "CredentialStore",
    "CustomScheduleTarget",
    "DrawnCircle",
    "JoystickCommand",
    "JsonlAuditLog",
    "MapEnvironmentAction",
    "MapEnvironmentCommand",
    "MapPoint",
    "MaticClient",
    "MaticConfig",
    "MergeRooms",
    "MissionPosture",
    "NavigationCommand",
    "NavigationMode",
    "RawCollectionEvent",
    "RawMotorCommand",
    "RemoveZones",
    "RenameRoom",
    "ReprioritizationSnapshot",
    "ReprioritizeAction",
    "ReprioritizeCoverageCommand",
    "RoomLabel",
    "ScheduleAction",
    "ScheduleCommand",
    "ScheduleCoverageSetting",
    "ScheduleDuration",
    "ScheduleEnabledState",
    "ScheduleEvent",
    "ScheduleEventKey",
    "ScheduleTime",
    "SecurityMode",
    "SemanticsOverride",
    "SemanticsOverrideKind",
    "SinkSummonLocation",
    "SinkSummonScheduleEvent",
    "SplitRoom",
    "StainMode",
    "StandardScheduleTarget",
    "TlsConfig",
    "UserAction",
    "UserCommand",
    "Weekday",
    "__version__",
]
